### ISSUE TITLE
could not make it work

### ISSUE THREAD

**Issue by revington** [butopea/vue-storefront-opencart-indexer#1]
With opencart 2x and ES 7.10.2
Having lots of these: 
```
Rejecting mapping update to [vue_storefront_catalog_3] as the final mapping would have more than 1 type: [attribute, product]"}]
```

**Comment by themreza** [comment]
Hi
This indexer was designed to work with Vue Storefront 1.11.x and ElasticSearch 5.6.
I haven't tested it yet on ElasticSearch 7, but it looks like it's due to a breaking change starting from ElasticSearch 6.

Please take a look at this StackOverflow question: https://stackoverflow.com/questions/50820309/elasticsearch-6-rejecting-mapping-update-as-the-final-mapping-would-have-more-t

**Comment by revington** [comment]
Hi @themreza thanks for a fast response. 

I see, I'll downgrade to @5.6
Thank you!
